chore(ci): improve formatting

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -23,16 +23,20 @@ pack:
     - npm pack
     - ARTIFACT_FILES=$(ls *.zip *.tgz *.stx 2>/dev/null || true)
     - |
-      if [ -z "$ARTIFACT_FILES" ]; then echo "Error: No artifacts found."; exit 1; fi
+      if [ -z "$ARTIFACT_FILES" ]; then
+        echo "Error: No artifacts found."
+        exit 1
+      fi
     - |
       echo "Found artifacts: $ARTIFACT_FILES"
     - |
       for file in $ARTIFACT_FILES; do
         curl --header "JOB-TOKEN: $CI_JOB_TOKEN" \
-             --upload-file "$file" \
-             "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${CI_PROJECT_NAME}/${CI_COMMIT_TAG}/$file"
+          --upload-file "$file" \
+          "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${CI_PROJECT_NAME}/${CI_COMMIT_TAG}/$file"
       done
-    - echo "$ARTIFACT_FILES" | tr ' ' '\n' > artifacts.txt
+    - |
+      echo "$ARTIFACT_FILES" | tr ' ' '\n' > artifacts.txt
   artifacts:
     paths:
       - artifacts.txt
